config/routes.rb
Rails.application.routes.draw do
  resources :project_status_histories
  resources :comments
  resources :projects
  devise_for :users

  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates_presence_of :message
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :project_status_histories, -> { order(created_at: :desc) }, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name

  STATUSES = %w[Draft Pending Published Deleted].freeze
end

app/models/project_status_history.rb
class ProjectStatusHistory < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments/new
  def new
    @comment = Comment.new
    @project_id = params[:project]
  end


  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @project_id = @comment.project_id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to project_url(@comment.project), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:message, :user_id, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      status = @project.status
      if @project.update(project_params)
        if status != @project.status
          handle_status_change
        end
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :status)
    end

    def handle_status_change
      ProjectStatusHistory.create! project: @project, user: current_user, status: @project.status
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |f| %>
  <div class="card">
    <div class="card-body">
      <% if comment.errors.any? %>
        <div style="color: red">
          <p><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</p>

          <ul>
            <% comment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.hidden_field :project_id, value: @project_id %>

      <div class="mb-3">
        <%= f.label :message, { class: "form-label"} %>
        <%= f.text_area :message, { class: "form-control", placeholder: "Add comment details here" } %>
      </div>

      <%= f.submit "Submit", class: "btn btn-primary" %>

    </div>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Project Manager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user.present? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <% link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Projects', projects_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>Project Manager</title>

   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
 </head>

 <body>
    <%= render 'layouts/navigation' %>

    <main role="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
 </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |f| %>
  <div class="card">
    <div class="card-body">
      <% if project.errors.any? %>
        <div style="color: red">
          <p><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</p>

          <ul>
            <% project.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= f.label :name, { class: "form-label"} %>
        <%= f.text_field :name, { class: "form-control", placeholder: "Project Name" } %>
      </div>

      <div class="mb-3">
        <%= f.label :status, { class: "form-label"} %>
        <%= f.select :status, options_for_select(Project::STATUSES, selected: project.status ), { }, { class: "form-select" } %>
      </div>

      <%= f.submit "Submit", class: "btn btn-primary" %>

    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= project.status %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Project Manager Dashboard</h1>
        <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <h1 class="card-title"><%= pluralize(@projects.count, 'project') %></h1>

                  <div class="card-body">
                    <%= link_to 'Add new project', new_project_path, class: 'btn btn-primary' %>
                    <table class="table table-striped">
                      <thead>
                      <tr>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Last updated</th>
                        <th>Comment count</th>
                        <th></th>
                      </tr>
                      </thead>
                      <tbody>
                      <% @projects.each do |project| %>
                        <tr>
                          <td><%= project.name %></td>
                          <td><%= project.status %></td>
                          <td><%= project.updated_at %></td>
                          <td><%= project.comments.count %></td>
                          <td><%= link_to 'Edit', edit_project_path(project) %></td>
                        </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card">
  <div class="card-body">
    <h1 class="card-title"><%= @project.name %></h1>

    <div class="card-body">
      <p>
        Status: <%= @project.status %>
      </p>

        <%= link_to "Add comment", new_comment_path(project: @project) %> |
        <%= link_to "Edit this project", edit_project_path(@project) %> |
        <%= link_to "Back to projects", projects_path %>

        <%= button_to "Destroy this project", @project, method: :delete, class: 'btn btn-secondary' %>
    </div>

  </div>
</div>


<div class="row">
  <div class="col-md-6">
    <h5>Comment History</h5>
    <% @project.comments.each do |comment| %>
      <div class="card">
        <div class="card-body">
          <p>
            <%= comment.user.email %> commented at <%= comment.created_at %>
            <%= comment.message %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <h5>Status Update History</h5>
    <% @project.project_status_histories.each do |status_history| %>
      <div class="card">
        <div class="card-body">
          <p>
            <%= status_history.user.email %> updated status to <%= status_history.status %> at <%= status_history.created_at %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>